import type { Question } from "./types"

export const questions: Question[] = [
  {
    id: 1,
    field: "age",
    question: "Quel est votre âge ?",
    icon: "👤",
    type: "number",
    required: true,
    helpText: "Les enfants de moins de 5 ans sont plus à risque",
    placeholder: "Entrez votre âge en années",
  },
  {
    id: 2,
    field: "hasFever",
    question: "Avez-vous de la fièvre actuellement ?",
    icon: "🤒",
    type: "radio",
    required: true,
    options: [
      { label: "Oui, j'ai de la fièvre", value: true },
      { label: "Non, pas de fièvre", value: false },
    ],
  },
  {
    id: 3,
    field: "temperature",
    question: "Quelle est votre température corporelle ?",
    icon: "🌡️",
    type: "number",
    required: true,
    helpText: "Température normale : 36.5-37.5°C",
    placeholder: "Ex: 38.5",
  },
  {
    id: 4,
    field: "troubleConsciousness",
    question: "Avez-vous des troubles de la conscience ?",
    icon: "😵",
    type: "radio",
    required: true,
    helpText: "Confusion, somnolence excessive, difficulté à rester éveillé",
    options: [
      { label: "Oui", value: true },
      { label: "Non", value: false },
    ],
  },
  {
    id: 5,
    field: "convulsions",
    question: "Avez-vous eu des convulsions récemment ?",
    icon: "⚡",
    type: "radio",
    required: true,
    helpText: "Crises convulsives dans les dernières 24 heures",
    options: [
      { label: "Oui", value: true },
      { label: "Non", value: false },
    ],
  },
  {
    id: 6,
    field: "symptoms",
    question: "Présentez-vous l'un de ces symptômes ?",
    icon: "🩺",
    type: "checkbox",
    required: false,
    helpText: "Cochez tous les symptômes qui s'appliquent",
    checkboxes: [
      { label: "Anémie sévère (pâleur extrême)", field: "severeAnemia" },
      { label: "Détresse respiratoire (difficulté à respirer)", field: "respiratoryDistress" },
      { label: "Ictère (jaunisse)", field: "jaundice" },
      { label: "Hémoglobinurie (urines foncées)", field: "hemoglobinuria" },
    ],
  },
  {
    id: 7,
    field: "hasParasitemia",
    question: "Avez-vous fait un test de paludisme (TDR) ?",
    icon: "🔬",
    type: "radio",
    required: true,
    helpText: "Test de Diagnostic Rapide ou goutte épaisse",
    options: [
      { label: "Oui, test positif", value: true },
      { label: "Non ou test négatif", value: false },
    ],
  },
  {
    id: 8,
    field: "parasitemiaLevel",
    question: "Si positif, quel est le taux de parasitémie ?",
    icon: "📊",
    type: "number",
    required: false,
    helpText: "Pourcentage de globules rouges infectés (si connu)",
    placeholder: "Ex: 5.2",
  },
]
